<script setup lang="ts">
definePageMeta({ layout: 'admin', middleware: 'admin' })
const { data: customers, pending, refresh } = await useFetch<any[]>('/api/admin/customers')
const search = ref(''); const statusFilter = ref('ACTIVOS'); const selected = ref<any | null>(null); const detail = ref<any | null>(null); const deleteTarget = ref<any | null>(null); const message = ref(''); const errorMessage = ref(''); const saving = ref(false)
const form = reactive({ name: '', phone: '', country: '', address: '', city: '', department: '', additional: '' })
const filteredCustomers = computed(() => (customers.value || []).filter(entry => (statusFilter.value === 'TODOS' || (statusFilter.value === 'ELIMINADOS' ? entry.customer.deletedAt : !entry.customer.deletedAt)) && `${entry.customer.name} ${entry.customer.phone}`.toLowerCase().includes(search.value.toLowerCase())))
const money = (value: number) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(value)
const openCustomer = async (entry: any) => { errorMessage.value = ''; try { detail.value = await $fetch(`/api/admin/customers/${encodeURIComponent(entry._id)}`); selected.value = entry; Object.assign(form, { name: detail.value.customer.name, phone: detail.value.customer.phone, country: detail.value.delivery.country || 'Colombia', address: detail.value.delivery.address, city: detail.value.delivery.city, department: detail.value.delivery.department, additional: detail.value.delivery.additional || '' }) } catch (error: any) { errorMessage.value = error?.data?.message || 'No se pudo cargar el cliente.' } }
const closeCustomer = () => { selected.value = null; detail.value = null }
const saveCustomer = async () => { if (!selected.value) return; saving.value = true; errorMessage.value = ''; try { await $fetch(`/api/admin/customers/${encodeURIComponent(selected.value._id)}`, { method: 'PATCH', body: form }); message.value = 'Cliente actualizado correctamente.'; await refresh(); await openCustomer({ _id: form.phone }) } catch (error: any) { errorMessage.value = error?.data?.message || 'No fue posible actualizar el cliente.' } finally { saving.value = false } }
const deleteCustomer = async () => { if (!deleteTarget.value) return; const phone = deleteTarget.value._id; try { await $fetch(`/api/admin/customers/${encodeURIComponent(phone)}`, { method: 'DELETE' }); message.value = 'Cliente eliminado lógicamente; sus pedidos se conservaron.'; deleteTarget.value = null; await refresh(); if (selected.value?._id === phone) closeCustomer() } catch (error: any) { errorMessage.value = error?.data?.message || 'No se pudo eliminar el cliente.'; deleteTarget.value = null } }
</script>

<template>
  <div class="admin-page"><div class="admin-page-heading"><div><p class="eyebrow">RELACIONES</p><h1>Clientes</h1><p>Gestiona los datos de contacto sin destruir el historial de pedidos.</p></div></div><div class="admin-management-toolbar"><label class="product-search"><span>⌕</span><input v-model="search" type="search" placeholder="Buscar por nombre o teléfono"></label><select v-model="statusFilter"><option value="ACTIVOS">Activos</option><option value="ELIMINADOS">Eliminados</option><option value="TODOS">Todos</option></select><span>{{ filteredCustomers.length }} clientes</span></div><p v-if="message" class="form-success product-page-message">{{ message }}</p><p v-if="errorMessage && !selected" class="form-error">{{ errorMessage }}</p><div v-if="pending" class="admin-loading">Cargando clientes...</div><div v-else class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Cliente</th><th>Contacto</th><th>Ubicación</th><th>Solicitudes</th><th>Total acumulado</th><th>Última solicitud</th><th>Acciones</th></tr></thead><tbody><tr v-for="entry in filteredCustomers" :key="entry._id"><td><strong>{{ entry.customer.name }}</strong></td><td>{{ entry.customer.phone }}<small>{{ entry.customer.email || 'Sin correo' }}</small></td><td>{{ entry.delivery.city }}<small>{{ entry.delivery.department }}</small></td><td>{{ entry.orders }}</td><td>{{ money(entry.total) }}</td><td>{{ new Date(entry.lastOrderAt).toLocaleDateString('es-CO') }}</td><td><div class="product-actions"><button class="table-action" @click="openCustomer(entry)">Ver / Editar</button><button class="table-action product-delete-action" @click="deleteTarget = entry">Eliminar</button></div></td></tr></tbody></table><div v-if="!filteredCustomers.length" class="empty-state"><h2>Aún no hay clientes</h2><p>Aparecerán cuando recibas solicitudes.</p></div></div>
    <div v-if="selected && detail" class="admin-modal-backdrop" @click.self="closeCustomer"><section class="admin-modal customer-detail-modal" role="dialog" aria-modal="true"><div class="card-heading"><div><p class="eyebrow">CLIENTE</p><h2>{{ form.name }}</h2></div><button type="button" class="drawer-close" aria-label="Cerrar" @click="closeCustomer">×</button></div><p v-if="errorMessage" class="form-error">{{ errorMessage }}</p><div class="form-row"><label>Nombre<input v-model="form.name" required></label><label>Teléfono<input v-model="form.phone" required></label></div><div class="form-row"><label>País<input v-model="form.country" required></label><label>Departamento<input v-model="form.department" required></label></div><div class="form-row"><label>Ciudad<input v-model="form.city" required></label><label>Dirección<input v-model="form.address" required></label></div><label>Información adicional<textarea v-model="form.additional" rows="2"></textarea></label><h3>Historial de pedidos</h3><div class="order-history"><p v-for="order in detail.orders" :key="order._id"><strong>{{ order.orderNumber }}</strong><small>{{ new Date(order.createdAt).toLocaleString('es-CO') }} · {{ order.status }} · {{ money(order.total) }}</small></p></div><div class="admin-modal-actions"><button type="button" class="button is-light" @click="closeCustomer">Cerrar</button><button type="button" class="button publication-save" :disabled="saving" @click="saveCustomer">{{ saving ? 'Guardando...' : 'Guardar cambios' }}</button></div></section></div>
    <div v-if="deleteTarget" class="admin-modal-backdrop" @click.self="deleteTarget = null"><section class="admin-modal" role="dialog" aria-modal="true"><h2>¿Eliminar cliente?</h2><p>Este cliente tiene <strong>{{ deleteTarget.orders }} pedidos asociados</strong>. Los pedidos no se eliminarán y el historial se conservará.</p><div class="admin-modal-actions"><button type="button" class="button is-light" @click="deleteTarget = null">Cancelar</button><button type="button" class="button product-delete-button" @click="deleteCustomer">Eliminar cliente</button></div></section></div>
  </div>
</template>
