<script setup lang="ts">
definePageMeta({ layout: 'admin', middleware: 'admin' })
const { data, pending, error, refresh } = await useFetch<any>('/api/admin/dashboard')
const cards = [{ label: 'Solicitudes nuevas', key: 'SOLICITUD RECIBIDA', tone: 'blue', link: '/admin/pedidos' }, { label: 'En revisión', key: 'EN REVISIÓN', tone: 'amber', link: '/admin/pedidos' }, { label: 'Pedidos activados', key: 'PEDIDO ACTIVADO', tone: 'violet', link: '/admin/pedidos' }, { label: 'Entregados', key: 'ENTREGADO', tone: 'green', link: '/admin/pedidos' }]
const money = (value: number) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(value)
const statusClass = (status: string) => `dashboard-status dashboard-status-${status.toLowerCase().replaceAll(' ', '-')}`
</script>

<template>
  <div class="admin-page dashboard-page">
    <div class="dashboard-welcome"><div><p class="eyebrow">RESUMEN OPERATIVO</p><h1>Buenos días, NUVIB.</h1><p>Este es el pulso de tu tienda hoy.</p></div><div class="dashboard-actions"><button class="dashboard-refresh" aria-label="Actualizar dashboard" @click="refresh">↻ <span>Actualizar</span></button><NuxtLink to="/admin/pedidos" class="button dashboard-primary">Ver pedidos <span>↗</span></NuxtLink></div></div>
    <div v-if="pending" class="dashboard-loading"><span class="loading-dot"></span> Cargando resumen...</div><div v-else-if="error" class="form-error dashboard-error">No se pudo cargar el dashboard. <button @click="refresh">Reintentar</button></div><template v-else>
      <div class="dashboard-highlight"><div class="highlight-copy"><span class="highlight-label">ACTIVIDAD DE HOY</span><strong>{{ data?.todayOrders || 0 }} <small>solicitudes</small></strong><p>Gestiona cada solicitud con calma y claridad.</p></div><div class="highlight-metrics"><div><span>Personas ahora</span><strong>{{ data?.activeVisitors || 0 }}</strong><NuxtLink to="/admin/monitor">Ver monitor →</NuxtLink></div><div><span>Productos activos</span><strong>{{ data?.products || 0 }}</strong><NuxtLink to="/admin/productos">Gestionar →</NuxtLink></div><div><span>Publicaciones</span><strong>{{ data?.publications || 0 }}</strong><NuxtLink to="/admin/publicaciones">Ver contenido →</NuxtLink></div></div></div>
      <div class="dashboard-section-title"><div><span class="card-kicker">PEDIDOS</span><h2>Estado de la operación</h2></div><NuxtLink to="/admin/pedidos">Ver todos →</NuxtLink></div><div class="dashboard-stat-grid"><NuxtLink v-for="card in cards" :key="card.key" :to="card.link" class="dashboard-stat-card" :class="`tone-${card.tone}`"><span class="dashboard-stat-icon">{{ card.tone === 'green' ? '✓' : card.tone === 'amber' ? '◷' : card.tone === 'violet' ? '↗' : '!' }}</span><span class="dashboard-stat-label">{{ card.label }}</span><strong>{{ data?.statuses?.[card.key] || 0 }}</strong><small>Ver solicitudes <b>→</b></small></NuxtLink></div>
      <div class="dashboard-lower-grid"><section class="dashboard-panel"><div class="dashboard-panel-heading"><div><span class="card-kicker">ACTIVIDAD RECIENTE</span><h2>Últimos pedidos</h2></div><NuxtLink to="/admin/pedidos">Ver todos</NuxtLink></div><div v-if="!data?.recentOrders?.length" class="dashboard-empty"><span>✦</span><p>Aún no hay pedidos.</p><small>Las nuevas solicitudes aparecerán aquí.</small></div><NuxtLink v-for="order in data?.recentOrders" :key="order._id" to="/admin/pedidos" class="dashboard-order-row"><div class="order-avatar">{{ order.customer?.name?.charAt(0)?.toUpperCase() || 'N' }}</div><div class="order-summary"><strong>{{ order.customer?.name }}</strong><small>{{ order.orderNumber }} · {{ new Date(order.createdAt).toLocaleDateString('es-CO') }}</small></div><div class="order-total"><strong>{{ money(order.total) }}</strong><span :class="statusClass(order.status)">{{ order.status }}</span></div><span class="row-arrow">→</span></NuxtLink></section><section class="dashboard-panel dashboard-guide"><span class="card-kicker">ACCESOS RÁPIDOS</span><h2>¿Qué quieres hacer?</h2><NuxtLink to="/admin/productos"><span class="quick-icon">▦</span><div><strong>Agregar producto</strong><small>Amplía tu catálogo</small></div><b>→</b></NuxtLink><NuxtLink to="/admin/publicaciones"><span class="quick-icon">✎</span><div><strong>Crear contenido</strong><small>Conecta con tus clientes</small></div><b>→</b></NuxtLink><NuxtLink to="/admin/monitor"><span class="quick-icon">◌</span><div><strong>Revisar actividad</strong><small>Conoce a tus visitantes</small></div><b>→</b></NuxtLink></section></div>
    </template>
  </div>
</template>
