<script setup lang="ts">
definePageMeta({ layout: 'admin', middleware: 'admin' })

const { data: orders, pending, refresh } = await useFetch<any[]>('/api/admin/orders')
const statusOptions = ['SOLICITUD RECIBIDA', 'EN REVISIÓN', 'CONTACTANDO CLIENTE', 'CONFIRMADO', 'PEDIDO ACTIVADO', 'EN PREPARACIÓN', 'DESPACHADO', 'EN CAMINO', 'ENTREGADO', 'PAGADO', 'CANCELADO', 'NO CONFIRMADO']
const search = ref(''); const statusFilter = ref('TODOS'); const selectedOrder = ref<any | null>(null); const detail = ref<any | null>(null); const deleteTarget = ref<any | null>(null); const saving = ref(false); const message = ref(''); const errorMessage = ref('')
const editForm = reactive({ name: '', phone: '', department: '', city: '', address: '', additional: '', status: '', note: '' })
const money = (value: number) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(value)
const filteredOrders = computed(() => (orders.value || []).filter(order => (statusFilter.value === 'TODOS' || (statusFilter.value === 'ELIMINADOS' ? order.deletedAt : order.status === statusFilter.value)) && `${order.orderNumber} ${order.customer?.name || ''} ${order.customer?.phone || ''}`.toLowerCase().includes(search.value.toLowerCase())))

const openOrder = async (order: any) => {
  errorMessage.value = ''
  try { detail.value = await $fetch(`/api/admin/orders/${order._id}`); selectedOrder.value = order; Object.assign(editForm, { name: detail.value.order.customer.name, phone: detail.value.order.customer.phone, department: detail.value.order.delivery.department, city: detail.value.order.delivery.city, address: detail.value.order.delivery.address, additional: detail.value.order.delivery.additional || '', status: detail.value.order.status, note: '' }) } catch (error: any) { errorMessage.value = error?.data?.message || 'No se pudo cargar el pedido.' }
}
const closeOrder = () => { selectedOrder.value = null; detail.value = null }
const saveOrder = async () => {
  if (!selectedOrder.value) return
  saving.value = true; errorMessage.value = ''
  try { await $fetch(`/api/admin/orders/${selectedOrder.value._id}`, { method: 'PATCH', body: { customer: { name: editForm.name, phone: editForm.phone }, delivery: { department: editForm.department, city: editForm.city, address: editForm.address, additional: editForm.additional }, status: editForm.status, note: editForm.note } }); message.value = 'Pedido actualizado correctamente.'; await refresh(); const current = orders.value?.find(item => item._id === selectedOrder.value?._id); if (current) await openOrder(current) } catch (error: any) { errorMessage.value = error?.data?.message || 'No fue posible actualizar el pedido.' } finally { saving.value = false }
}
const cancelOrder = async () => { if (!selectedOrder.value || !window.confirm('¿Cancelar pedido? El historial se conservará.')) return; editForm.status = 'CANCELADO'; await saveOrder() }
const deleteOrder = async () => { if (!deleteTarget.value || !window.confirm('¿Eliminar pedido? Se conservará de forma lógica en el historial.')) return; const deletedId = deleteTarget.value._id; try { await $fetch(`/api/admin/orders/${deletedId}`, { method: 'DELETE' }); message.value = 'Pedido eliminado lógicamente y conservado en el historial.'; deleteTarget.value = null; await refresh(); if (selectedOrder.value?._id === deletedId) closeOrder() } catch (error: any) { errorMessage.value = error?.data?.message || 'No se pudo eliminar el pedido.'; deleteTarget.value = null } }
const copyOrder = async (order: any) => { const source = detail.value?.order?._id === order._id ? detail.value : await $fetch<any>(`/api/admin/orders/${order._id}`); const text = [`PEDIDO NUVIB: ${source.order.orderNumber}`, '', `CLIENTE: ${source.order.customer.name}`, `Teléfono: ${source.order.customer.phone}`, `ENTREGA: ${source.order.delivery.address}, ${source.order.delivery.city}, ${source.order.delivery.department}`, '', 'PRODUCTOS:', ...source.items.map((item: any) => `${item.name}${item.size ? ` | Talla: ${item.size}` : ''}${item.color ? ` | Color: ${item.color}` : ''} | Cantidad: ${item.quantity} | Precio: ${money(item.price)}`), '', `TOTAL: ${money(source.order.total)}`, `ESTADO: ${source.order.status}`].join('\n'); await navigator.clipboard.writeText(text); message.value = 'Datos del pedido copiados.' }
</script>

<template>
  <div class="admin-page">
    <div class="admin-page-heading"><div><p class="eyebrow">OPERACIÓN</p><h1>Pedidos</h1><p>Revisa, edita y actualiza cada solicitud sin perder su historial.</p></div><button class="button is-light" @click="refresh">Actualizar</button></div>
    <div class="admin-management-toolbar"><label class="product-search"><span>⌕</span><input v-model="search" type="search" placeholder="Buscar pedido, cliente o teléfono"></label><select v-model="statusFilter"><option value="TODOS">Todos los estados</option><option value="ELIMINADOS">Eliminados</option><option v-for="status in statusOptions" :key="status" :value="status">{{ status }}</option></select><span>{{ filteredOrders.length }} pedidos</span></div>
    <p v-if="message" class="form-success product-page-message">{{ message }}</p><p v-if="errorMessage && !selectedOrder" class="form-error">{{ errorMessage }}</p>
    <div v-if="pending" class="admin-loading">Cargando pedidos...</div>
    <div v-else class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Solicitud</th><th>Cliente</th><th>Ubicación</th><th>Total</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><tr v-for="order in filteredOrders" :key="order._id"><td><strong>{{ order.orderNumber }}</strong><small>{{ new Date(order.createdAt).toLocaleString('es-CO') }}</small></td><td><strong>{{ order.customer.name }}</strong><small>{{ order.customer.phone }}</small></td><td>{{ order.delivery.city }}<small>{{ order.delivery.department }}</small></td><td>{{ money(order.total) }}</td><td><span class="product-status" :class="`order-status-${order.status.toLowerCase().replaceAll(' ', '-')}`">{{ order.status }}</span></td><td><div class="product-actions"><button class="table-action" @click="openOrder(order)">Ver / Editar</button><button class="table-action" @click="copyOrder(order)">Copiar</button><button class="table-action product-delete-action" @click="deleteTarget = order">Eliminar</button></div></td></tr></tbody></table><div v-if="!filteredOrders.length" class="empty-state"><h2>Aún no hay solicitudes</h2><p>Aparecerán cuando recibas pedidos.</p></div></div>
    <div v-if="selectedOrder && detail" class="admin-modal-backdrop" @click.self="closeOrder"><section class="admin-modal order-detail-modal" role="dialog" aria-modal="true"><div class="card-heading"><div><p class="eyebrow">PEDIDO {{ detail.order.orderNumber }}</p><h2>Ver / editar pedido</h2></div><button type="button" class="drawer-close" aria-label="Cerrar" @click="closeOrder">×</button></div><p v-if="errorMessage" class="form-error">{{ errorMessage }}</p><div class="order-detail-items"><article v-for="item in detail.items" :key="item._id"><div><strong>{{ item.name }}</strong><small>{{ item.sku || 'Sin SKU' }} · Cantidad: {{ item.quantity }}</small></div><strong>{{ money(item.total) }}</strong></article></div><div class="form-row"><label>Cliente<input v-model="editForm.name" required></label><label>Teléfono<input v-model="editForm.phone" required></label></div><div class="form-row"><label>Departamento<input v-model="editForm.department" required></label><label>Ciudad<input v-model="editForm.city" required></label></div><label>Dirección<textarea v-model="editForm.address" rows="2" required></textarea></label><label>Información adicional<textarea v-model="editForm.additional" rows="2"></textarea></label><div class="form-row"><label>Estado<select v-model="editForm.status"><option v-for="status in statusOptions" :key="status" :value="status">{{ status }}</option></select></label><label>Nota administrativa<input v-model="editForm.note" placeholder="Opcional"></label></div><div class="thanks-meta"><div><span>Subtotal</span><strong>{{ money(detail.order.subtotal) }}</strong></div><div><span>Envío</span><strong>{{ money(detail.order.shipping || 0) }}</strong></div><div><span>Total</span><strong>{{ money(detail.order.total) }}</strong></div></div><h3>Historial de estados</h3><div class="order-history"><p v-for="entry in detail.history" :key="entry._id"><strong>{{ entry.status }}</strong><small>{{ new Date(entry.changedAt).toLocaleString('es-CO') }} · {{ entry.actor || 'sistema' }}</small></p></div><div class="admin-modal-actions"><button type="button" class="button is-light" @click="closeOrder">Cerrar</button><button type="button" class="button is-light" @click="cancelOrder">Cancelar pedido</button><button type="button" class="button publication-save" :disabled="saving" @click="saveOrder">{{ saving ? 'Guardando...' : 'Guardar cambios' }}</button></div></section></div>
    <div v-if="deleteTarget" class="admin-modal-backdrop" @click.self="deleteTarget = null"><section class="admin-modal" role="dialog" aria-modal="true"><h2>¿Eliminar pedido?</h2><p>El pedido se conservará de forma lógica para mantener el historial.</p><div class="admin-modal-actions"><button type="button" class="button is-light" @click="deleteTarget = null">Cancelar</button><button type="button" class="button product-delete-button" @click="deleteOrder">Eliminar pedido</button></div></section></div>
  </div>
</template>
