<script setup lang="ts">
definePageMeta({ layout: 'admin', middleware: 'admin' })

const statusFilter = ref('TODOS')
const sourceFilter = ref('TODOS')
const message = ref('')
const errorMessage = ref('')
const editingId = ref('')
const editComment = ref('')
const externalForm = reactive({ productId: '', customerName: '', sourceName: '', sourceUrl: '', sourceReviewId: '', rating: 5, comment: '' })
const { data: reviews, refresh } = await useFetch<any[]>('/api/admin/reviews')
const { data: productData } = await useFetch<any>('/api/admin/products')
const filteredReviews = computed(() => (reviews.value || []).filter(review => (statusFilter.value === 'TODOS' || review.status === statusFilter.value) && (sourceFilter.value === 'TODOS' || review.source === sourceFilter.value)))
const stars = (rating: number) => '★'.repeat(rating) + '☆'.repeat(5 - rating)
const moderate = async (review: any, status: string, comment?: string) => { try { await $fetch(`/api/admin/reviews/${review._id}`, { method: 'PATCH', body: { status, comment } }); editingId.value = ''; message.value = `Reseña ${status.toLowerCase()}.`; await refresh() } catch (error: any) { errorMessage.value = error?.data?.message || 'No se pudo moderar la reseña.' } }
const removeReview = async (review: any) => { if (!window.confirm('¿Eliminar esta reseña definitivamente?')) return; try { await $fetch(`/api/admin/reviews/${review._id}`, { method: 'DELETE' }); message.value = 'Reseña eliminada.'; await refresh() } catch (error: any) { errorMessage.value = error?.data?.message || 'No se pudo eliminar la reseña.' } }
const beginEdit = (review: any) => { editingId.value = review._id; editComment.value = review.comment }
const importExternal = async () => { errorMessage.value = ''; try { await $fetch('/api/admin/reviews', { method: 'POST', body: externalForm }); message.value = 'Opinión externa importada como pendiente.'; Object.assign(externalForm, { productId: '', customerName: '', sourceName: '', sourceUrl: '', sourceReviewId: '', rating: 5, comment: '' }); await refresh() } catch (error: any) { errorMessage.value = error?.data?.message || 'No se pudo importar la opinión.' } }
const syncAll = async () => { errorMessage.value = ''; try { const result = await $fetch<{ processed: number; synchronized: number; errors: any[] }>('/api/admin/reviews/sync-all', { method: 'POST' }); message.value = `${result.synchronized} de ${result.processed} productos sincronizados.`; if (result.errors.length) errorMessage.value = 'Algunos productos no pudieron sincronizarse; sus reseñas anteriores continúan visibles.'; await refresh() } catch (error: any) { errorMessage.value = error?.data?.message || 'No fue posible iniciar la sincronización.' } }
</script>

<template>
  <div class="admin-page">
    <div class="admin-page-heading"><div><p class="eyebrow">CONFIANZA</p><h1>Reseñas</h1><p>Modera opiniones reales y conserva separadas las fuentes externas.</p></div><button class="button dashboard-primary" type="button" @click="syncAll">Sincronizar todo</button></div>
    <div class="admin-management-toolbar"><select v-model="statusFilter"><option value="TODOS">Todos los estados</option><option>PENDIENTE</option><option>PUBLICADA</option><option>RECHAZADA</option><option>OCULTA</option></select><select v-model="sourceFilter"><option value="TODOS">Todas las fuentes</option><option value="NUVIB">Clientes NUVIB</option><option value="EXTERNA">Externas</option></select><span>{{ filteredReviews.length }} reseñas</span></div>
    <p v-if="message" class="form-success product-page-message">{{ message }}</p><p v-if="errorMessage" class="form-error">{{ errorMessage }}</p>
    <div class="admin-form-card review-admin-import"><div class="card-heading"><div><span class="card-kicker">FUENTE AUTORIZADA</span><h2>Importar opinión externa</h2></div></div><form class="form-grid" @submit.prevent="importExternal"><label>Producto<select v-model="externalForm.productId" required><option value="">Selecciona un producto</option><option v-for="product in productData?.products || []" :key="product._id" :value="product._id">{{ product.name }}</option></select></label><label>Plataforma / fuente<input v-model="externalForm.sourceName" required placeholder="Ej. Plataforma autorizada"></label><label>Autor mostrado<input v-model="externalForm.customerName" placeholder="Nombre mostrado"></label><label>Calificación<select v-model.number="externalForm.rating"><option v-for="level in [5,4,3,2,1]" :key="level" :value="level">{{ stars(level) }}</option></select></label><label>URL de origen<input v-model="externalForm.sourceUrl" type="url"></label><label>ID externo<input v-model="externalForm.sourceReviewId"></label><label class="form-span-2">Comentario<textarea v-model="externalForm.comment" required minlength="5" rows="3"></textarea></label><button class="button publication-save">Importar pendiente</button></form></div>
    <section class="review-admin-list"><article v-for="review in filteredReviews" :key="review._id" class="admin-review-card"><div class="admin-review-top"><div><strong>{{ stars(review.rating) }}</strong><span class="product-status">{{ review.status }}</span><span :class="review.source === 'EXTERNA' ? 'external-badge' : 'verified-badge'">{{ review.source === 'EXTERNA' ? `Opinión externa · ${review.sourceName}` : review.verifiedPurchase ? 'Compra verificada' : 'Cliente NUVIB' }}</span></div><small>{{ new Date(review.createdAt).toLocaleString('es-CO') }}</small></div><h3>{{ review.productName }}</h3><p v-if="editingId !== review._id">“{{ review.comment }}”</p><div v-else><textarea v-model="editComment" rows="4" class="review-edit-input"></textarea></div><footer><span>{{ review.customerName }}</span><span v-if="review.editedByAdmin">Editada por administración</span><a v-if="review.sourceUrl" :href="review.sourceUrl" target="_blank" rel="noopener">Ver fuente</a></footer><img v-if="review.imageUrl" class="review-photo" :src="review.imageUrl" alt="Imagen enviada con la reseña"><div class="product-actions"><button v-if="editingId !== review._id" class="table-action" @click="beginEdit(review)">Editar</button><button v-else class="table-action" @click="moderate(review, review.status, editComment)">Guardar edición</button><button class="table-action" @click="moderate(review, 'PUBLICADA')">Publicar</button><button class="table-action" @click="moderate(review, 'OCULTA')">Ocultar</button><button class="table-action product-delete-action" @click="moderate(review, 'RECHAZADA')">Rechazar</button><button class="table-action product-delete-action" @click="removeReview(review)">Eliminar</button></div></article><div v-if="!filteredReviews.length" class="empty-state"><h2>No hay reseñas con estos filtros</h2></div></section>
  </div>
</template>
