<script setup lang="ts">
definePageMeta({ layout: 'admin', middleware: 'admin' })
const { data: settings } = await useFetch<any>('/api/admin/conversion'); const saving = ref(false); const message = ref(''); const errorMessage = ref('')
const save = async () => { saving.value = true; errorMessage.value = ''; try { Object.assign(settings.value, await $fetch('/api/admin/conversion', { method: 'PATCH', body: settings.value })); message.value = 'Configuración de conversión guardada.' } catch (error: any) { errorMessage.value = error?.data?.message || 'No se pudo guardar la configuración.' } finally { saving.value = false } }
</script>

<template>
  <div class="admin-page"><div class="admin-page-heading"><div><p class="eyebrow">CONFIGURACIÓN</p><h1>Conversión visual</h1><p>Activa únicamente mensajes respaldados por visitas, pedidos, stock y ofertas reales.</p></div></div><form v-if="settings" class="admin-form-card conversion-settings" @submit.prevent="save"><div class="form-row"><label class="toggle-label"><span><strong>Estrategia activa</strong><small>Permite mostrar señales reales en la tienda.</small></span><input v-model="settings.enabled" type="checkbox" class="toggle-input"><i class="toggle-track"></i></label><label class="toggle-label"><span><strong>Notificaciones flotantes</strong><small>Se ocultan si no hay actividad suficiente.</small></span><input v-model="settings.notifications" type="checkbox" class="toggle-input"><i class="toggle-track"></i></label></div><fieldset><legend>Módulos visibles</legend><div class="conversion-settings-grid"><label v-for="item in [{ key: 'activeViewers', label: 'Personas viendo' }, { key: 'visits', label: 'Visitas reales' }, { key: 'orders', label: 'Actividad de pedidos' }, { key: 'offers', label: 'Ofertas con fecha' }, { key: 'stockAlerts', label: 'Alertas de disponibles' }, { key: 'availabilityBar', label: 'Barra de disponibilidad' }, { key: 'socialProof', label: 'Prueba social' }, { key: 'trustMessages', label: 'Mensajes de confianza' }]" :key="item.key" class="toggle-label"><span><strong>{{ item.label }}</strong></span><input v-model="settings[item.key]" type="checkbox" class="toggle-input"><i class="toggle-track"></i></label></div></fieldset><fieldset><legend>Frecuencia y límites</legend><div class="form-row"><label>Duración de notificación (segundos)<input v-model.number="settings.notificationDuration" type="number" min="3" max="15"></label><label>Intervalo mínimo (segundos)<input v-model.number="settings.notificationInterval" type="number" min="20" max="600"></label></div><div class="form-row"><label>Máximo por sesión<input v-model.number="settings.maxNotificationsPerSession" type="number" min="0" max="10"></label><label>Límite de disponibles<input v-model.number="settings.stockThreshold" type="number" min="0" max="100"></label></div><div class="form-row"><label>Base de la barra de disponibilidad<input v-model.number="settings.availabilityBase" type="number" min="1" max="10000"></label><label class="toggle-label"><span><strong>Mostrar en móvil</strong></span><input v-model="settings.showOnMobile" type="checkbox" class="toggle-input"><i class="toggle-track"></i></label></div><label class="toggle-label"><span><strong>Mostrar en escritorio</strong></span><input v-model="settings.showOnDesktop" type="checkbox" class="toggle-input"><i class="toggle-track"></i></label></fieldset><p v-if="message" class="form-success">{{ message }}</p><p v-if="errorMessage" class="form-error">{{ errorMessage }}</p><button class="button publication-save" :disabled="saving">{{ saving ? 'Guardando...' : 'Guardar configuración' }}</button></form></div>
</template>
